# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Francois's tech blog
email: francois.misslin@gmail.com
description: >
  Francois's tech blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://framis.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  framis

# Build settings
markdown: kramdown
excerpt_separator: Read more...
